spring:
  mvc:
    cors:
      allow-credentials: true
      allowed-origins: http://localhost:3001
      allowed-methods: GET,POST,PUT,DELETE
      allowed-headers: Content-Type,Authorization
  cloud:
    gateway:
      routes:
        - id: insta-actions-be
          uri: lb://INSTA-ACTIONS-BE
          predicates:
            - Path=/api/v1/comment/**, /api/v1/follow/**
          filters:
          - AuthenticationFilter
        - id: insta-authorization-server
          uri: lb://INSTA-AUTHORIZATION-SERVER
          predicates:
            - Path=/api/v1/auth/**, /user/**
          filters:
          - AuthenticationFilter
        - id: insta-image-be
          uri: lb://INSTA-IMAGE-BE
          predicates:
            - Path=/api/v1/image/**
          filters:
          - AuthenticationFilter
  application:
     name: insta-api-gateway
server:
  port: 8888
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/