spring:
  mvc:
    cors:
      allow-credentials: true
      allowed-origins: "http://localhost:3001"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "Content-Type,Authorization"
  datasource:
    url: jdbc:mysql://localhost:3306/insta
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: insta-image-be
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost