spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insta
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: insta-comment-be
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
