spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insta
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: insta-authorization-server
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost