spring:
  mvc:
    cors:
      allow-credentials: true
      allowed-origins: http://localhost:3001
      allowed-methods: GET,POST,PUT,DELETE
      allowed-headers: Content-Type,Authorization
  datasource:
    url: jdbc:mysql://localhost:3306/insta
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: insta-actions-be
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: COMMENT
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
